### ISSUE TITLE
Error running it

### ISSUE THREAD

**Issue by filviu** [mdp/GistEvernoteImport#1]
Believe it or not I'd like to be the fourth in the line of people using this. I installed ruby (hopefully correctly), followed the installation instructions and configured config.yml 

When I run it I'm getting an error:

``` bash
ruby import.rb 
"Querying Gist API for page #1"
/home/user/opt/GistEvernoteImport/gists.rb:19:in `get': undefined method `[]' for nil:NilClass (NoMethodError)
        from import.rb:11:in `<main>'
```

Unfortunately ruby is completely foreign to me. Any ideas what I might be doing wrong?

Cheers,
Silviu

P.S. I use two factor auth on github so I generated a "Personal Token" and I installed ruby using this guide: http://computers.tutsplus.com/tutorials/how-to-install-ruby-on-rails-on-raspberry-pi--cms-21421 up to the "JavaScript Runtime" part which I assumed I don't need.

**Comment by mdp** [comment]
Sorry, just now saw this, I'm assuming at this point you've either given up or gotten it working :)

This error is probably because it can't find the Folder you've configured. I've updated the code to improve the error message.
