### ISSUE TITLE
Adding syntax highlighting

### ISSUE THREAD

**Issue by shinnkondo** [mdp/GistEvernoteImport#5]
I have two questions.
1. Is it OK to add a gem which requires python to `Gemfile` and `require` it in `gist.rb`?
2. Does it sound good to add an option for a highlighting style in `config.yaml`?

(For Q1) I chose to use [pygment.rb](https://github.com/tmm1/pygments.rb) for highlighting because it covers more languages than other options.
However, it needs python to be installed in the system, which creates additional (and possibly unnecessary) dependency for this script.  And I have no idea at which point it returns an error when python does not exist in the system.

(For Q2) Also, to preserve the original option, I'm thinking about adding new option in the YAML file to specify a highlighting style( `code_highlighting_style: 'default'`, for example). If it is not specified, the script runs without highlighting, using the original way.

**Comment by mdp** [comment]
Sorry, I'm not actively maintaining this at the moment. Feel free to take it over.
